version: '3'

services:
  reverse-proxy:
    image: traefik
    container_name: traefik
    command: --web --docker --docker.domain=changeme.com --logLevel=INFO
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/traefik.toml
      - ./config/acme.json:/acme.json
      labels:
      - traefik.frontend.rule=Host:traefik.changeme.com
      - traefik.port=8080
    networks:
      - web
    restart: always

networks:
  web:
    external: true
