version: '3'

services:
   portainer:
      image: portainer/portainer
      container_name: portainer
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./data:/data
      labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=Host:www"
      networks:
        - web
      restart: always

networks:
   web:
     external: true
